# Generated by Django 5.2.3 on 2025-07-09 15:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener exactamente 10 dígitos.', regex='^\\d{10}$')])),
                ('direccion', models.CharField(max_length=255)),
                ('empresa', models.CharField(blank=True, max_length=255, null=True)),
                ('persona_contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(max_length=100)),
                ('rfc', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='El RFC no tiene el formato correcto', regex='^[A-ZÑ&]{4}\\d{6}[A-Z0-9]{3}$')])),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('proyecto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_proyecto', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.TextField()),
                ('sector', models.CharField(max_length=100)),
                ('costo_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarifa_porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tarifa_monto', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('utilidad_total', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scayflow.cliente')),
            ],
            options={
                'db_table': 'proyectos',
            },
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('tramite_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('tarifa_monto', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True)),
                ('costo_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarifa_porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_tramite', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True)),
                ('duracion_estimada', models.IntegerField()),
                ('tiempo_resolucion', models.IntegerField()),
                ('dependencia', models.CharField(max_length=255)),
                ('responsable_dependencia', models.CharField(max_length=255)),
                ('estatus', models.CharField(max_length=50)),
                ('documentos_requeridos', models.TextField()),
                ('observaciones', models.TextField()),
                ('fecha_ultima_actualizacion', models.DateField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramites', to='scayflow.proyecto')),
            ],
            options={
                'db_table': 'tramites',
            },
        ),
    ]
