# Generated by Django 5.2.3 on 2025-07-07 20:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scayflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rfc',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='El RFC no tiene el formato correcto', regex='^[A-ZÑ&]{4}\\d{6}[A-Z0-9]{3}$')]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener exactamente 10 dígitos.', regex='^\\d{10}$')]),
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('proyecto_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_proyecto', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descripcion', models.TextField()),
                ('sector', models.CharField(max_length=100)),
                ('costo_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarifa_porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tarifa_monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('nota', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scayflow.cliente')),
            ],
            options={
                'db_table': 'proyectos',
            },
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('tramite_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('costo_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tarifa_porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_tramite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duracion_estimada', models.CharField(max_length=50)),
                ('tiempo_resolucion', models.CharField(max_length=50)),
                ('dependencia', models.CharField(max_length=255)),
                ('responsable_dependecnia', models.CharField(max_length=255)),
                ('estatus', models.CharField(max_length=50)),
                ('documentos_requeridos', models.TextField()),
                ('observaciones', models.TextField()),
                ('fecha_ultima_actualizacion', models.DateField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramites', to='scayflow.proyecto')),
            ],
            options={
                'db_table': 'tramites',
            },
        ),
    ]
