# Generated by Django 5.2.3 on 2025-07-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scayflow', '0003_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='verificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pago',
            name='comprobante',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='pago',
            table='pagos',
        ),
    ]
