# Generated by Django 5.2.3 on 2025-07-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scayflow', '0004_pago_verificado_alter_pago_comprobante_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='id',
        ),
        migrations.AddField(
            model_name='pago',
            name='pago_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
