# Generated by Django 5.2.3 on 2025-07-09 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scayflow', '0005_remove_pago_id_pago_pago_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='verificado',
        ),
    ]
